name: testing561

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        
      - name: Setup Go
        uses:  actions/setup-go@v7
        with:
          go-version-file: go.mod
          
